<a href="https://colab.research.google.com/github/yuriborg/scikit_learn_beginner_tutorial/blob/main/calculo_numerico_resumo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zeros de Funções

## Método da Bissecção/Dicotomia

In [ ]:
#Programa Python para um exemplo dado em aula.

#Queremos achar o zero da funcao abaixo
def f(x):
    return x**3+4*x**2-10

#[a,b] o intervalo, p=p0 e N o numero de iteracoes.
a = 1
b = 2
p = a+(b-a)/2
N = 3

#Metodo da bissecao feito abaixo:
i = 0
while i<N:
    if f(p)==0:
        break
    elif f(a)*f(p)<0:
        b = p
        p = a+(b-a)/2
    else:
        a = p
        p = a+(b-a)/2
    i = i+1

#Imprimimos os valores de an, bn e pn. Distinguimos o caso em que se acha
#o zero e o caso em que sao feitas todas as N iteracoes.

if f(p)==0:
    print("p{} foi obtido exatamente e igual a {}".format(i,p))
else:
    print("Apos {} iteracoes:".format(N))
    print("a{} igual a {}".format(N,a))
    print("b{} igual a {}".format(N,b))
    print("p{} igual a {}".format(N,p))

Apos 3 iteracoes:
a3 igual a 1.25
b3 igual a 1.375
p3 igual a 1.3125


## Método do Ponto Fixo / Método de Aproximações Sucessivas (MAS)

In [ ]:
#Programa Python para um exemplo dado em aula.
#Usaremos o numpy para o cosseno. Poderiamos usar math tambem.
import numpy as np

#Queremos achar um ponto fixo da funcao abaixo.
def g(x):
    return np.cos(x)

#N e o numero de iteracoes, p o valor inicial.
N = 5
p = 444.44
i = 0

#Aqui imprimimos p0. Usamos \t para adicionar espaco.
print("p{} igual a \t {}".format(i,p))

#Aqui estamos calulando e imprimindo pi, para i>0.
for i in range(N):
    p = g(p)
    print("p{} igual a \t {}".format(i+1,p))

p0 igual a 	 444.44
p1 igual a 	 -0.09521601996297555
p2 igual a 	 0.995470378486244
p3 igual a 	 0.5441082951012782
p4 igual a 	 0.8555892266982379
p5 igual a 	 0.6557737825194007


## Método de Convergência Alternada

In [ ]:
# Programa em Python para exemplo de metodo iterativo de convergencia alternada

# ---------------------------------------------------------------------------

#Usamos o numpy apenas para usar a funcao modulo (np.abs)
import numpy as np

#Abaixo segue a funcao que queremos achar o ponto fixo
def g(x):
    return 2.08/(x+0.96)
#p e o ponto inicial, epsilon e o erro maximo que queremos e
#i indica o numero de iteracoes
p = 0.5
print("p0 igual a \t {}".format(p))
epsilon = 0.04
i = 1
#O metodo so para quando |p-phi(p)|<=2*epsilon
while (np.abs(g(p)-p)>2*epsilon):
    p = g(p)
    print("p{} igual a \t {}".format(i,p))
    i = i+1
#Abaixo imprimimos o valor de phi(p) com o p final
print("g(p{}) igual a \t {}".format(i-1,g(p)))
#p abaixo e o nosso p final
p = (p+g(p))/2
print("pfinal igual a \t {}".format(p))


# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------


# Programa em Python para um exemplo de metodo iterativo de convergencia monotona

# ---------------------------------------------------------------------------

#Abaixo segue a funcao que queremos achar o ponto fixo
def g(x):
    return x+(2-x*x)/4

#p e o ponto inicial, epsilon e o erro maximo que queremos e
#i indica o numero de iteracoes
p = 0.5
epsilon = 0.03
print("p0 igual a \t {}".format(p))
i = 1
#O metodo so para quando g(p+2*epsilon)<=p+2*epsilon
while g(p+2*epsilon)>p+2*epsilon:
    p = g(p+2*epsilon)
    print("p{} igual a \t {}".format(i,p))
    i = i+1
#p abaixo e o nosso p final
p = p + epsilon
print("pfinal igual a \t {}".format(p))

p0 igual a 	 0.5
p1 igual a 	 1.4246575342465755
p2 igual a 	 0.8722426470588235
p3 igual a 	 1.1352208198727853
p4 igual a 	 0.9927354578913982
g(p4) igual a 	 1.0651724439141514
pfinal igual a 	 1.0289539509027747
p0 igual a 	 0.5
p1 igual a 	 0.9816
p2 igual a 	 1.27036736
p3 igual a 	 1.3878980318616576
pfinal igual a 	 1.4178980318616576


## Método de Newton-Raphson

In [ ]:
#Método de Newton para calcular raiz de 2

#Queremos achar o zero da função x*x-2 usando o método de Newton

#Abaixo, fixamos o nosso p0 e o número de iterações N
p = 3.0
N = 10
print("p0 é igual a {}".format(p))

#A cada nova iteração, fazemos p = p - (p*p-2)/2*p
for i in range(N):
    p= p/2+1/p
    print("p{} é igual a {}".format(i+1,p))

# -----------------------------------------------------------

#Método de Newton com aceleração para calcular raiz de 2

#Queremos achar o zero da função x*x-2 usando o método de Newton com aceleração

#Abaixo damos o nosso p0 e o máximo erro que queremos E
#i conta o número de iterações
p = 3.0
E = 0.01
i = 0
print("p0 é igual a {}".format(p))

#A cada nova iteração, fazemos p = p-2*E - ((p-2*E)*(p-2*E)-2)/(2*(p-2*E))
#Paramos apenas quando f(p-2*E)<=0
while ((p-2*E)*(p-2*E)-2)>0:
    p = (p-2*E)/2+1/(p-2*E)
    i = i+1
    print("p{} é igual a {}".format(i+1,p))
print("O p final é igual a {}".format(p-E))

p0 é igual a 3.0
p1 é igual a 1.8333333333333333
p2 é igual a 1.4621212121212122
p3 é igual a 1.414998429894803
p4 é igual a 1.4142137800471977
p5 é igual a 1.4142135623731118
p6 é igual a 1.414213562373095
p7 é igual a 1.414213562373095
p8 é igual a 1.414213562373095
p9 é igual a 1.414213562373095
p10 é igual a 1.414213562373095
p0 é igual a 3.0
p2 é igual a 1.8255704697986577
p3 é igual a 1.4566268139053875
p4 é igual a 1.414388400347504
O p final é igual a 1.404388400347504


# Resolução de Sistemas Lineares

## Escalonamento

In [ ]:
#Abaixo vamos escalonar o exemplo 1 dado em sala de aula.
#O método abaixo apenas funciona para escalonamentos de matrizes que não requerem de mudanças de linhas.

#Código Python com explicações:


'''
Método de eliminação de Gauss para quando não é necessário troca de linhas.
O algoritmo é:
Para k = 1,...,n:
    Para j=k+1,...,n:
        Lj vira Lj - (ajk/akk)*Lk
'''

import numpy as np

#Abaixo A é a matriz aumentada. N é o número de linhas da matriz A
n = 4
A = [[1.,1.,0.,3.,4.],[2.,1.,-1.,1.,1.],[3.,-1.,-1.,2.,-3.],[-1.,2.,3.,-1.,4.]]
A = np.array(A)
print("A matriz original é")
print(A)

for k in range(n):
    for j in range(k+1,n):
        # Abaixo estamos fazendo Lj vira Lj - (ajk/akk)*Lk
        m = A[j,k]/A[k,k]
        # Também podemos usar A[j,:] = A[j,:]-m*A[k,:] ao invés do que foi feito abaixo
        for l in range(n+1):
            A[j,l] = A[j,l]-m*A[k,l]
print("\nA matriz escalonada é")
print(A)
'''
Para achar a solução, fazemos
para j = n,n-1,...,1:
    xj=(bj-(somatória de k=j+1 a n (ajk*xk)))/ajj
'''
#x é o vetor solução. Começamos definindo um vetor com n zeros.
x = np.zeros(n)
#Aqui j vai de n-1, n-2, ..., até 0
for j in range(n-1,-1,-1):
    #somatoria será igual a (somatória de k=j+1 a n (ajk*xk))
    somatoria =  0
    for k in range(j+1,n):
        somatoria = somatoria + A[j,k]*x[k]
    #Aqui calculamos xj
    x[j]=(A[j,n]-somatoria)/A[j,j]
print("\nA solução é")
print(x)

A matriz original é
[[ 1.  1.  0.  3.  4.]
 [ 2.  1. -1.  1.  1.]
 [ 3. -1. -1.  2. -3.]
 [-1.  2.  3. -1.  4.]]

A matriz escalonada é
[[  1.   1.   0.   3.   4.]
 [  0.  -1.  -1.  -5.  -7.]
 [  0.   0.   3.  13.  13.]
 [  0.   0.   0. -13. -13.]]

A solução é
[-1.  2.  0.  1.]


## Método de Jacobi

In [ ]:
#Método de Jacobi

import numpy as np

#Escolhemos o tamanho da matriz n x n e o número de iterações Nit
n = 4
Nit = 3
#Abaixo estão as matrizes A, b e nosso x0, que no caso é igual ao vetor 0
A = np.array([[10.,-1.,2.,0.],[-1.,11.,-1,3.],[2.,-1.,10.,-1.],[0.,3.,-1.,8.]])
b = np.array([6.,25.,-11.,15.])
x = np.zeros(4)
#y irá nos ajudar a guardar a nova iteração
y = np.zeros(n)
print("x0 é igual a")
print(x)
#O primeiro for é responsável por fazer Nit iterações
for k in range(Nit):
#O segundo for é para escrever cada x(k+1)_j em função dos x(k)_js
    for j in range(n):
        l = 0
        somatoria = 0
#o terceiro for é só para fazer a somatória
        for l in range(n):
            if l!=j:
                somatoria = somatoria + A[j,l]*x[l]
        y[j] = (b[j] - somatoria)/A[j,j]
#Cuidado ao copiar o vetor y no x. Se você escrever x = y, então x e y viram o
#mesmo vetor. Tudo o que se fizer em um, vai fazer no outro também. Para copiar,
#use np.copy().
    x = np.copy(y)
    print("\nx{} é igual a ".format(k+1))
    print(x)

## Método de Gauss-Siedel

In [ ]:
#Método de Gauss-Seidel

import numpy as np

#Escolhemos o tamanho da matriz n x n e o número de iterações Nit
n = 3
Nit = 2
#Abaixo estão as matrizes A, b e nosso x0, que no caso é igual ao vetor 0
A = np.array([[4.,1.,1.],[-2.,5.,1.],[3.,1.,6.]])
b = np.array([5.,0.,-6.5])
x = np.zeros(3)
print("x0 é igual a")
print(x)
#O primeiro for é responsável por fazer Nit iterações
for k in range(Nit):
#O segundo for é para escrever cada x(k+1)_j em função dos x(k)_js
#Note que, aqui no Gauss-Seidel, os novos x_js são colocados no x_js antigo
    for j in range(n):
        l = 0
        somatoria = 0
#o terceiro for é só para fazer a somatória
        for l in range(n):
            if l!=j:
                somatoria = somatoria + A[j,l]*x[l]
        x[j] = (b[j] - somatoria)/A[j,j]
    print("\nx{} é igual a ".format(k+1))
    print(x)

x0 é igual a
[0. 0. 0.]

x1 é igual a 
[ 1.25        0.5        -1.79166667]

x2 é igual a 
[ 1.57291667  0.9875     -2.034375  ]


## Critério de Sassenfield (Minimização de Erro)

In [ ]:
#Abaixo vamos achar os coeficientes de uma reta y = ax+b que minimizem os erros quadrátricos

#Vamos usar além do numpy, o matplotlib para plotar os dados e a reta
import numpy as np
import matplotlib.pyplot as plt

#Os dados x,y são dados abaixo. n indica o número de pontos
x = np.array([0.,1.,2.,3.,4.])
y = np.array([0.,1.,1.,4.,4.])
n = 5

#Abaixo xx indica a soma dos xi^2, xy a soma dos xiyi, x1 a soma dos xi e y1 a soma dos yi
xx = 0
xy = 0
x1 = 0
y1 = 0

#Cada um dos for abaixo é para fazer as somatórias
for i in range(5):
    xx = xx + x[i]*x[i]
for i in range(5):
    xy = xy + x[i]*y[i]
for i in range(5):
    x1 = x1 + x[i]
for i in range(5):
    y1 = y1 + y[i]

#a e b são os coeficientes da reta y = ax+b
b = (xx*y1-x1*xy)/(n*xx-x1**2)
a = (n*xy-x1*y1)/(n*xx-x1**2)

#Abaixo imprimimos os resultados
print("Os coeficientes da reta y = ax+b são")
print("a = {}".format(a))
print("b = {}".format(b))

#Abaixo plotamos os pontos x e y com cor verde "go"
plt.plot(x,y,"go")

#Abaixo definimos a fórmula da reta e depois plotamos a reta em azul entre 0 e 4
def reta(x):
    return a*x+b
z = np.linspace(0,4,10)
plt.plot(z,reta(z),color="blue")

## Eliminação de Gauss

In [ ]:
#Abaixo um programa para resolver a um dos exemplos dados em sala de aula.

import numpy as np
import matplotlib.pyplot as plt

#Aqui é a função que resolve o sistema dado pela matriz (aumentada) A.
#O método usado é a eliminação de Gauss. Do jeito que está,
#só consegue resolver sistemas que não precisem de trocas de linhas.
def solucaosistema(A):
    n = A.shape[0]
    for k in range(n):
        for j in range(k+1,n):
            m = A[j,k]/A[k,k]
            for l in range(n+1):
                A[j,l] = A[j,l]-m*A[k,l]
    x = np.zeros(n)
    for j in range(n-1,-1,-1):
        somatoria = 0
        for k in range(j+1,n):
            somatoria = somatoria + A[j,k]*x[k]
        x[j]=(A[j,n]-somatoria)/A[j,j]
    return(x)

#Aqui definimos as funções 1, x e x*x
def g(j,x):
    if j==0:
        return x-x+1
    if j==1:
        return x
    if j==2:
        return x*x

#Aqui definimos a função produto interno
def prod(a,b):
    soma = 0
    for i in range(n):
        soma = soma + a[i]*b[i]
    return soma

#n é o número de dados.
#Nf é o número de funções. Aqui Nf = 3, pois temos as funções 1, x, x*x.
n = 5
nf = 3

#Aqui temos os nossos dados x e y
x = np.array([0.,0.25,0.5,0.75,1.0])
y = np.array([1.0,1.284,1.6487,2.1170,2.7183])

#Aqui montamos uma matriz cujas linhas são os vetores w0, w1, w2 formados pela
#aplicação das funções g no vetor x.
w = np.zeros([nf,n])
for i in range(nf):
    w[i,:] = g(i,x)

#Agora vamos definir a matriz A que representará o sistema normal
A = np.zeros([nf,nf+1])
for i in range(nf):
    for j in range(nf):
        A[i,j] = prod(w[i,:],w[j,:])
for i in range(nf):
    A[i,nf] = prod(w[i,:],y)

#Aqui imprimimos o sistema normal
print("\nO sistema normal é dado pela matriz abaixo:\n")
print(A)

#Aqui resolvemos o sistema normal e imprimimos a sua solução
sol = solucaosistema(A)
print("\nA função dada pelo MMQ é y(x)=a+b*x+c*x**2, em que\n")
print("a = {}\nb = {}\nc = {}".format(sol[0],sol[1],sol[2]))

#Aqui plotamos nossos dados x e y
plt.plot(x,y,'go')

#Aqui plotamos a função encontrada pelo MMQ
def funcao(x):
    return sol[0]+sol[1]*x+sol[2]*x*x
t = np.linspace(0,1)
plt.plot(t,funcao(t))


# Método dos Mínimos Quadrados


## Série de Fourier (Polinômio Trigonométrico Contínuo)

In [ ]:
#Abaixo as figuras plotadas nas notas de aula

'''
---------------------------------------------------------------
Exemplo de série de Fourier (polinômio trigonométrico contínuo)
---------------------------------------------------------------
'''

import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return x

def S(x,n):
    s = 0
    for i in range(1,n+1):
        s = s + (2/i)*(-1)**(i+1)*np.sin(i*x)
    return s

t = np.linspace(-np.pi,np.pi,1000)
f, = plt.plot(t,f(t))
S1, = plt.plot(t,S(t,1))
S2, = plt.plot(t,S(t,2))
S10, = plt.plot(t,S(t,20))
plt.legend([f,S1,S2,S10],["função","Série 1 termo","Série 2 termos","Série 20 termos"])

'''
---------------------------------------------------------------
Exemplo de polinômio trigonométrico discreto
---------------------------------------------------------------


import numpy as np
import matplotlib.pyplot as plt

def f(x):
    return 2*x**2-9

def S(x):
    return (1/2)*(-4.109)-8.773*np.cos(x)+2.924*np.cos(2*x)

x = np.array([-np.pi,-2*np.pi/3,-np.pi/3,0,np.pi/3,2*np.pi/3])

p, = plt.plot(x,f(x),"go")
t = np.linspace(-np.pi,np.pi,1000)
f, = plt.plot(t,f(t),color='blue')
S, = plt.plot(t,S(t),color='red')

plt.legend([f,S,p],["função","Aproximação","pontos"])


---------------------------------------------------------------
Exemplo usando polinômios ortogonais
---------------------------------------------------------------


import numpy as np
import matplotlib.pyplot as plt

#Polinômio ortogonal
def f(x):
    return np.e**x

def g(x):
    return 3*(13*np.e-35)+12*(49-18*np.e)*x+30*(7*np.e-19)*x**2

def h(x):
    return np.e-1+6*(3-np.e)*(x-1/2)+30*(7*np.e-19)*(x**2-x+1/6)

t = np.linspace(-0.1,1.1)
f, = plt.plot(t,f(t),color='blue')
g, = plt.plot(t,g(t),color='red')
plt.legend([f,g],["função","aproximação polinomial"])
'''

# Interpolação

In [ ]:
#Abaixo segue o programa usado em aula para plotar as funções em Python.

import numpy as np
import matplotlib.pyplot as plt

def interpolar():
    x = np.array([2.0,2.75,4.0])
    y = np.array([1/2,1/2.75,1/4])
    def f(x):
        return 1/x
    def p(x):
        return x**2/22-35*x/88+49/44
    s = np.linspace(2.,4.)
    fu, = plt.plot(s,f(s))
    pol, = plt.plot(s,p(s))
    pontos, = plt.plot(x,y,'go')
    plt.legend([fu,pol,pontos],["função f","polinômio interpolador","pontos"])

def resto():
    def W(x):
        return (x-2)*(x-2.75)*(x-4)
    t = np.linspace(2,4)
    plt.plot(t,W(t))

x = int(input("O que deseja?\n(1) para gráfico do polinômio de interpolação\n\
(2) para gráfico do resto\n"))

if x==1:
    interpolar()
if x==2:
    resto()